name: Publish Docker images to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push back
      run: |
        cd back
        docker build -t ghcr.io/foxandxss/demo-pablo-back:latest .
        docker push ghcr.io/foxandxss/demo-pablo-back:latest

    - name: Build and push front
      run: |
        cd front
        docker build -t ghcr.io/foxandxss/demo-pablo-front:latest .
        docker push ghcr.io/foxandxss/demo-pablo-front:latest
